cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .maven/
stages:
  - build
  - test
  - analyze
  - package
  - release
  - deploy

before_script:
  - $NG_CLI_ANALYTICS="false"
  - $MAVEN_USER_HOME=".maven"
  - ./mvnw com.github.eirslett:frontend-maven-plugin:install-node-and-npm -DnodeVersion="v10.16.0" -DnpmVersion="6.9.0" "-Dmaven.repo.local=$MAVEN_USER_HOME"
  - ./mvnw com.github.eirslett:frontend-maven-plugin:npm "-Dmaven.repo.local=$MAVEN_USER_HOME"

maven-compile:
  stage: build
  script:
    - ./mvnw compile "-Dmaven.repo.local=$MAVEN_USER_HOME"
  artifacts:
    paths:
      - target/classes/
      - target/generated-sources/
    expire_in: 1 day

maven-test:
  stage: test
  script:
    - ./mvnw verify "-Dmaven.repo.local=$MAVEN_USER_HOME"
  artifacts:
    reports:
      junit: target/test-results/**/TEST-*.xml
    paths:
      - target/test-results
      - target/jacoco
    expire_in: 1 day

frontend-test:
  stage: test
  script:
    - ./mvnw com.github.eirslett:frontend-maven-plugin:npm "-Dfrontend.npm.arguments=run test" "-Dmaven.repo.local=$MAVEN_USER_HOME"
  artifacts:
    reports:
      junit: target/test-results/TESTS-results-jest.xml
    paths:
      - target/test-results
      - target/jacoco
    expire_in: 1 day

maven-package:
  stage: package
  script:
    - ./mvnw verify -Pprod -DskipTests "-Dmaven.repo.local=$MAVEN_USER_HOME"
  artifacts:
    paths:
      - target/*.jar
      - target/classes
    expire_in: 1 day

# Uncomment the following line to use gitlabs container registry. You need to adapt the REGISTRY_URL in case you are not using gitlab.com
#docker-push:
#    stage: release
#    variables:
#        REGISTRY_URL: registry.gitlab.com
#        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#    dependencies:
#        - maven-package
#    script:
#        - ./mvnw jib:build -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=gitlab-ci-token  -Djib.to.auth.password=$CI_BUILD_TOKEN

deploy-to-production:
  stage: deploy
  script:
    - Write-Output $env:HEROKU_API_KEY
    - ./mvnw com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod "-Dheroku.buildpacks=heroku/jvm" "-Dheroku.appName=event-planner-internship" "-Dmaven.repo.local=$MAVEN_USER_HOME"
  environment:
    name: production
  when: manual
